import openai
from rich.console import Console
from models.card_listing import CardInfo, CardListing, ValidatedListing

console = Console()

VALIDATOR_SYSTEM_PROMPT = """You are a senior eBay sports card listing specialist and quality assurance expert. Your role is to critically review listings generated by other sellers and refine them to maximize sales performance.

You have a sharp eye for:
- eBay title SEO failures (missing keywords, wrong abbreviations, wasted characters, exceeding 80 chars)
- Pricing mistakes (too high causing no bids, too low leaving money on the table, wrong strategy for card type)
- Description weaknesses (vague condition notes, missing key selling points, poor structure, walls of text)
- Item specifics gaps that hurt search visibility
- Missing urgency or social proof that motivates buyers

You are direct and specific in your critiques. You don't just say "improve this" — you rewrite it better.

Your validation process:
1. Check the title: Is it under 80 chars? Does it lead with the most searchable terms? Does it include RC/Auto/serial/grade if applicable?
2. Evaluate pricing: Is this strategy right for this type of card? Are the dollar amounts realistic for current market?
3. Review the description: Is it complete, honest, and compelling? Does it build trust?
4. Assess item specifics: Are all relevant eBay categories filled?
5. Provide market context: What do buyers of this card specifically care about?

Your output should be a refined listing that is noticeably better than the draft, plus honest feedback on what was changed and why.

DESCRIPTION STYLE — all refined descriptions must match the voice of eBay seller maxmr17:
- Concise, confident, no-fluff tone. Facts first, hype never.
- Short punchy sentences. No walls of text.
- Lead with the card's key appeal (rookie year, investment-grade parallel, pop report, etc.)
- Condition described plainly and honestly — specific observations, not vague filler.
- Shipping/payment section kept brief and to the point.
- No excessive exclamation marks. Professional but personable."""


def _listing_to_text(listing: CardListing) -> str:
    """Convert a CardListing to a readable text format for the validator prompt."""
    pricing = listing.pricing
    strategy_str = pricing.strategy.value.replace("_", " ").title()

    price_parts = [f"Strategy: {strategy_str}"]
    if pricing.starting_price:
        price_parts.append(f"Starting Price: ${pricing.starting_price:.2f}")
    if pricing.buy_it_now_price:
        price_parts.append(f"Buy It Now: ${pricing.buy_it_now_price:.2f}")
    price_parts.append(f"Best Offer: {'Yes' if pricing.allow_offers else 'No'}")
    price_parts.append(f"Rationale: {pricing.pricing_rationale}")

    specifics_text = "\n".join(f"  {s.key}: {s.value}" for s in listing.item_specifics)

    return f"""TITLE ({len(listing.title)}/80 chars): {listing.title}
SUBTITLE: {listing.subtitle}
CONDITION GRADE: {listing.condition_grade}
CONDITION NOTES: {listing.condition_description}

PRICING:
{chr(10).join(f'  {p}' for p in price_parts)}

ITEM SPECIFICS:
{specifics_text}

SEARCH KEYWORDS: {', '.join(listing.search_keywords)}

DESCRIPTION:
{listing.description}"""


def validate_and_refine(
    card: CardInfo,
    draft_listing: CardListing,
    client: openai.OpenAI,
) -> ValidatedListing:
    """Run the validator agent to critique and refine a draft listing."""
    console.print("\n[bold yellow]🔍 Validator Agent running...[/bold yellow]")

    listing_text = _listing_to_text(draft_listing)

    user_message = f"""Review and refine this eBay sports card listing. Be rigorous — your job is to make it significantly better.

CARD BEING LISTED:
Player: {card.player_name} | Set: {card.card_set} | Card #: {card.card_number}
Sport: {card.sport} | Rookie: {card.is_rookie_card} | Auto: {card.is_autographed} | Graded: {card.is_graded}{f' ({card.grade})' if card.grade else ''}{f' | Serial: {card.serial_number}' if card.serial_number else ''}

DRAFT LISTING TO REVIEW:
{listing_text}

Scrutinize every element. Then produce a refined listing that maximizes buyer interest and final sale price. Include specific market insight about what collectors of this card care about."""

    response = client.beta.chat.completions.parse(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": VALIDATOR_SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
        response_format=ValidatedListing,
    )

    validated = response.choices[0].message.parsed
    if validated is None:
        raise ValueError("Validator agent returned no structured output")

    validated.original_listing = draft_listing

    console.print("[green]✓ Validation complete[/green]")
    return validated
